/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package practica10_pcd;

import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.Random;
import org.jcsp.lang.Any2OneChannel;
import org.jcsp.lang.Channel;
import org.jcsp.lang.One2OneChannel;
import org.jcsp.util.Buffer;

/**
 *
 * @author usuario
 */
public class Generador extends java.awt.Frame {

    /**
     * Creates new form NewFrame
     */
    public Generador() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     * @throws java.lang.InterruptedException
     */
    public static void main(String args[]) throws InterruptedException {
        
        int numanimales = 20, ancho = 1000, alto = 720;
        
        //Definimos los buzones
        Any2OneChannel entraPerro = Channel.any2one(new Buffer(numanimales));
        Any2OneChannel salePerro = Channel.any2one(new Buffer(numanimales));
        Any2OneChannel entraGato = Channel.any2one(new Buffer(numanimales));
        Any2OneChannel saleGato = Channel.any2one(new Buffer(numanimales));
        One2OneChannel permiso[] = new One2OneChannel[numanimales];
        
        for (int i = 0; i < numanimales; i++) {
            permiso[i] = Channel.one2one(new Buffer(1));
        }
        
        
        Generador f = new Generador();
        f.setSize(ancho, alto);
        f.setTitle("Practica 10 PCD");
        f.setLocation(500, 100);

        CanvasComedero cc = new CanvasComedero(ancho, alto);
        f.add(cc);
        f.setVisible(true);

        Thread[] animal = new Thread[numanimales];
        Gato g;
        Controlador c = new Controlador(entraPerro,salePerro,entraGato,saleGato,permiso);
        c.start();
        Random rnd = new Random();
        rnd.setSeed(System.currentTimeMillis());
        try {
            for (int i = 0; i < numanimales; i++) {
                if (rnd.nextInt(10) > 4) {
                    animal[i] = new Perro(c, cc, entraPerro, salePerro, permiso[i],i);
                    animal[i].start();
                } else {
                    g = new Gato(c, cc,entraGato, saleGato, permiso[i],i);
                    animal[i] = new Thread(g);
                    animal[i].start();
                }
                Thread.sleep((rnd.nextInt(1) + 1) * 1000);
            }
            for (int i = 0; i < numanimales; i++) {
                animal[i].join();
            }
        } catch (InterruptedException ex) {
            java.util.logging.Logger.getLogger(Generador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        System.exit(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
