/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author danie
 */
public class PanelActividades extends javax.swing.JPanel {

    /**
     * Creates new form PanelSocio
     */
    public PanelActividades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableActividades = new javax.swing.JTable();
        jLabelGestionSocios = new javax.swing.JLabel();
        jButtonNuevaActividad = new javax.swing.JButton();
        jButtonEliminarActividad = new javax.swing.JButton();
        jButtonActualizarActividad = new javax.swing.JButton();
        jButtonVerInscripciones = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jTableActividades.setBackground(new java.awt.Color(255, 255, 255));
        jTableActividades.setBorder(new javax.swing.border.MatteBorder(null));
        jTableActividades.setForeground(new java.awt.Color(0, 0, 0));
        jTableActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableActividades);

        jLabelGestionSocios.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabelGestionSocios.setForeground(new java.awt.Color(51, 204, 255));
        jLabelGestionSocios.setText("Gestión de Actividades");

        jButtonNuevaActividad.setBackground(new java.awt.Color(102, 204, 255));
        jButtonNuevaActividad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonNuevaActividad.setForeground(new java.awt.Color(0, 0, 0));
        jButtonNuevaActividad.setText("Nueva Actividad");
        jButtonNuevaActividad.setActionCommand("NuevaActividad");
        jButtonNuevaActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaActividadActionPerformed(evt);
            }
        });

        jButtonEliminarActividad.setBackground(new java.awt.Color(102, 204, 255));
        jButtonEliminarActividad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonEliminarActividad.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEliminarActividad.setText("Eliminar Actividad");
        jButtonEliminarActividad.setActionCommand("EliminaActividad");
        jButtonEliminarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActividadActionPerformed(evt);
            }
        });

        jButtonActualizarActividad.setBackground(new java.awt.Color(102, 204, 255));
        jButtonActualizarActividad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonActualizarActividad.setForeground(new java.awt.Color(0, 0, 0));
        jButtonActualizarActividad.setText("Actualizar Actividad");
        jButtonActualizarActividad.setActionCommand("ActualizacionActividad");

        jButtonVerInscripciones.setBackground(new java.awt.Color(102, 204, 255));
        jButtonVerInscripciones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonVerInscripciones.setForeground(new java.awt.Color(0, 0, 0));
        jButtonVerInscripciones.setText("Ver inscripciones");
        jButtonVerInscripciones.setActionCommand("VerInscripciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabelGestionSocios))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jButtonNuevaActividad)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEliminarActividad)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonActualizarActividad)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonVerInscripciones)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelGestionSocios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevaActividad)
                    .addComponent(jButtonEliminarActividad)
                    .addComponent(jButtonActualizarActividad)
                    .addComponent(jButtonVerInscripciones))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEliminarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarActividadActionPerformed

    private void jButtonNuevaActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNuevaActividadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonActualizarActividad;
    public javax.swing.JButton jButtonEliminarActividad;
    public javax.swing.JButton jButtonNuevaActividad;
    public javax.swing.JButton jButtonVerInscripciones;
    public javax.swing.JLabel jLabelGestionSocios;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableActividades;
    // End of variables declaration//GEN-END:variables
}
