/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author danie
 */
public class PanelMonitor extends javax.swing.JPanel {

    /**
     * Creates new form PanelMonitor
     */
    public PanelMonitor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMonitores = new javax.swing.JTable();
        jLabelGestionMonitores = new javax.swing.JLabel();
        jButtonNuevoMonitor = new javax.swing.JButton();
        jButtonBajaMonitor = new javax.swing.JButton();
        jButtonActualizacionMonitor = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        jTableMonitores.setBackground(new java.awt.Color(255, 255, 255));
        jTableMonitores.setBorder(new javax.swing.border.MatteBorder(null));
        jTableMonitores.setForeground(new java.awt.Color(0, 0, 0));
        jTableMonitores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMonitores);

        jLabelGestionMonitores.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabelGestionMonitores.setForeground(new java.awt.Color(51, 204, 255));
        jLabelGestionMonitores.setText("Gestión de Monitores");

        jButtonNuevoMonitor.setBackground(new java.awt.Color(102, 204, 255));
        jButtonNuevoMonitor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonNuevoMonitor.setForeground(new java.awt.Color(0, 0, 0));
        jButtonNuevoMonitor.setText("Nuevo Monitor");
        jButtonNuevoMonitor.setActionCommand("NuevoMonitor");

        jButtonBajaMonitor.setBackground(new java.awt.Color(102, 204, 255));
        jButtonBajaMonitor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBajaMonitor.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBajaMonitor.setText("Baja Monitor");
        jButtonBajaMonitor.setActionCommand("BajaMonitor");
        jButtonBajaMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaMonitorActionPerformed(evt);
            }
        });

        jButtonActualizacionMonitor.setBackground(new java.awt.Color(102, 204, 255));
        jButtonActualizacionMonitor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonActualizacionMonitor.setForeground(new java.awt.Color(0, 0, 0));
        jButtonActualizacionMonitor.setText("Actualizacion Monitor");
        jButtonActualizacionMonitor.setActionCommand("ActualizacionMonitor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButtonNuevoMonitor)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBajaMonitor)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonActualizacionMonitor)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelGestionMonitores)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelGestionMonitores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevoMonitor)
                    .addComponent(jButtonBajaMonitor)
                    .addComponent(jButtonActualizacionMonitor))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBajaMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaMonitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBajaMonitorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonActualizacionMonitor;
    public javax.swing.JButton jButtonBajaMonitor;
    public javax.swing.JButton jButtonNuevoMonitor;
    public javax.swing.JLabel jLabelGestionMonitores;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableMonitores;
    // End of variables declaration//GEN-END:variables
}
