/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

/**
 *
 * @author danie
 */
public class vistaLogin extends javax.swing.JFrame {

    /**
     * Creates new form vistaLogin
     */
    
    
    public vistaLogin() {
        initComponents();
        
        URL url = getClass().getResource("/imagenes/dumbell.png");
        if(url != null){
            Image icon = Toolkit.getDefaultToolkit().getImage(url);
            setIconImage(icon);
        }else{
            System.out.println("No se pudo encontrar el recurso");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackGround = new javax.swing.JPanel();
        jButtonConectar = new javax.swing.JButton();
        jComboBox1Servidores = new javax.swing.JComboBox<>();
        jButtonSalirDialogoConexion = new javax.swing.JButton();
        jLabelServidor = new javax.swing.JLabel();
        jLabelFotologin = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acceso a la aplicación");
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(0, 25, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanelBackGround.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBackGround.setForeground(new java.awt.Color(255, 255, 255));

        jButtonConectar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonConectar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButtonConectar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonConectar.setText("Conectar");
        jButtonConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConectarActionPerformed(evt);
            }
        });

        jComboBox1Servidores.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox1Servidores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1Servidores.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1Servidores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MariaDB", "Oracle" }));
        jComboBox1Servidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ServidoresActionPerformed(evt);
            }
        });

        jButtonSalirDialogoConexion.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSalirDialogoConexion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButtonSalirDialogoConexion.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSalirDialogoConexion.setText("Salir");
        jButtonSalirDialogoConexion.setActionCommand("SalirDialogoConexion");

        jLabelServidor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelServidor.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabelServidor.setForeground(new java.awt.Color(255, 51, 0));
        jLabelServidor.setText("Servidor:");

        jLabelFotologin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gymlogin.jpg"))); // NOI18N

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoGym.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelBackGroundLayout = new javax.swing.GroupLayout(jPanelBackGround);
        jPanelBackGround.setLayout(jPanelBackGroundLayout);
        jPanelBackGroundLayout.setHorizontalGroup(
            jPanelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackGroundLayout.createSequentialGroup()
                .addComponent(jLabelFotologin)
                .addGroup(jPanelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBackGroundLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonConectar)
                            .addComponent(jLabelServidor))
                        .addGroup(jPanelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBackGroundLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1Servidores, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(51, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackGroundLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSalirDialogoConexion)
                                .addGap(32, 32, 32))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackGroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelLogo)
                        .addGap(99, 99, 99))))
        );
        jPanelBackGroundLayout.setVerticalGroup(
            jPanelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackGroundLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabelLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelServidor)
                    .addComponent(jComboBox1Servidores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addGroup(jPanelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConectar)
                    .addComponent(jButtonSalirDialogoConexion))
                .addGap(41, 41, 41))
            .addGroup(jPanelBackGroundLayout.createSequentialGroup()
                .addComponent(jLabelFotologin, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackGround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConectarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConectarActionPerformed

    private void jComboBox1ServidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ServidoresActionPerformed

        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1ServidoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonConectar;
    public javax.swing.JButton jButtonSalirDialogoConexion;
    public javax.swing.JComboBox<String> jComboBox1Servidores;
    public javax.swing.JLabel jLabelFotologin;
    public javax.swing.JLabel jLabelLogo;
    public javax.swing.JLabel jLabelServidor;
    public javax.swing.JPanel jPanelBackGround;
    // End of variables declaration//GEN-END:variables
}
