/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author danie
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        
        URL url = getClass().getResource("/imagenes/dumbell.png");
        if(url != null){
            Image icon = Toolkit.getDefaultToolkit().getImage(url);
            setIconImage(icon);
        }else{
            System.out.println("No se pudo encontrar el recurso");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPanelPrincipal = new javax.swing.JMenu();
        jMenuItemCasa = new javax.swing.JMenuItem();
        jMenuMonitores = new javax.swing.JMenu();
        jMenuItemGestionMonitor = new javax.swing.JMenuItem();
        jMenuSocios = new javax.swing.JMenu();
        jMenuIGestionSocios = new javax.swing.JMenuItem();
        jMenuActividades = new javax.swing.JMenu();
        jMenuItemGestionActividades = new javax.swing.JMenuItem();
        jMenuAmpliacion = new javax.swing.JMenu();
        jMenuItemActualizacionCat = new javax.swing.JMenuItem();
        jMenuItemCuotaActividad = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        jMenuItemSalirAplicacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenuBar1.setBackground(new java.awt.Color(102, 204, 255));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setMargin(new java.awt.Insets(0, 5, 0, 0));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(291, 35000));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(291, 27));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(500, 30));
        jMenuBar1.setRequestFocusEnabled(false);

        jMenuPanelPrincipal.setText("🏠");
        jMenuPanelPrincipal.setActionCommand("PanelPrincipal\n");

        jMenuItemCasa.setText("Home");
        jMenuItemCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCasaActionPerformed(evt);
            }
        });
        jMenuPanelPrincipal.add(jMenuItemCasa);

        jMenuBar1.add(jMenuPanelPrincipal);

        jMenuMonitores.setText("Monitores");

        jMenuItemGestionMonitor.setText("Gestión de Monitores");
        jMenuItemGestionMonitor.setActionCommand("GestionMonitores");
        jMenuMonitores.add(jMenuItemGestionMonitor);

        jMenuBar1.add(jMenuMonitores);

        jMenuSocios.setText("Socios");

        jMenuIGestionSocios.setText("Gestión de Socios");
        jMenuIGestionSocios.setActionCommand("GestionSocios");
        jMenuSocios.add(jMenuIGestionSocios);

        jMenuBar1.add(jMenuSocios);

        jMenuActividades.setBackground(new java.awt.Color(0, 0, 0));
        jMenuActividades.setText("Actividades");

        jMenuItemGestionActividades.setText("Gestión de Actividades");
        jMenuItemGestionActividades.setActionCommand("GestionActividades");
        jMenuItemGestionActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionActividadesActionPerformed(evt);
            }
        });
        jMenuActividades.add(jMenuItemGestionActividades);

        jMenuBar1.add(jMenuActividades);

        jMenuAmpliacion.setText("Ampliación");

        jMenuItemActualizacionCat.setText("Actualización de Categorías");
        jMenuItemActualizacionCat.setActionCommand("ActualizacionCat");
        jMenuAmpliacion.add(jMenuItemActualizacionCat);

        jMenuItemCuotaActividad.setText("Cuota de Actividad");
        jMenuItemCuotaActividad.setActionCommand("CuotaActividad");
        jMenuAmpliacion.add(jMenuItemCuotaActividad);

        jMenuBar1.add(jMenuAmpliacion);

        jMenuSalir.setText("Salir");

        jMenuItemSalirAplicacion.setText("Salir de la aplicación");
        jMenuItemSalirAplicacion.setActionCommand("SalirAplicacion");
        jMenuSalir.add(jMenuItemSalirAplicacion);

        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 932, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCasaActionPerformed

    private void jMenuItemGestionActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionActividadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemGestionActividadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
       
        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu jMenuActividades;
    public javax.swing.JMenu jMenuAmpliacion;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuIGestionSocios;
    public javax.swing.JMenuItem jMenuItemActualizacionCat;
    public javax.swing.JMenuItem jMenuItemCasa;
    public javax.swing.JMenuItem jMenuItemCuotaActividad;
    public javax.swing.JMenuItem jMenuItemGestionActividades;
    public javax.swing.JMenuItem jMenuItemGestionMonitor;
    public javax.swing.JMenuItem jMenuItemSalirAplicacion;
    public javax.swing.JMenu jMenuMonitores;
    public javax.swing.JMenu jMenuPanelPrincipal;
    public javax.swing.JMenu jMenuSalir;
    public javax.swing.JMenu jMenuSocios;
    // End of variables declaration//GEN-END:variables
}
