package practica5_pcd;

import practica5_pcd.Centro;
import practica5_pcd.CanvasCentro;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
/**
 *
 * @author danie
 */
public class Generador extends java.awt.Frame {

    /**
     * Creates new form Practica5_Frame
     */
    public Generador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
            int ancho = 1000, alto = 720, numcli = 10;

            Generador f = new Generador();
            f.setSize(ancho, alto);
            f.setTitle("Practica 5 PCD");
            f.setLocation(500, 100);

            CanvasCentro cc = new CanvasCentro(ancho, alto);
            f.add(cc);
            f.setVisible(true);

            Thread[] cliente = new Thread[numcli];
            Rehabilita r;
            Centro c = new Centro();
            Random rnd = new Random();
            rnd.setSeed(System.currentTimeMillis());
            try {

                for (int i = 0; i < numcli; i++) {
                    if (rnd.nextInt(100) < 60) {
                        cliente[i] = new Masaje(c, cc);
                        cliente[i].start();
                    } else {
                        r = new Rehabilita(c, cc);
                        cliente[i] = new Thread(r);
                        cliente[i].start();
                    }
                    Thread.sleep((rnd.nextInt(2) + 1) * 1000);
                }
                for (int i = 0; i < numcli; i++) {
                    cliente[i].join();
                }

            } catch (InterruptedException ex) {
                Logger.getLogger(Generador.class.getName()).log(Level.SEVERE, null, ex);

            }
            System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
