/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author danie
 */
public class PanelSocio extends javax.swing.JPanel {

    /**
     * Creates new form PanelSocio
     */
    public PanelSocio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSocios = new javax.swing.JTable();
        jLabelGestionSocios = new javax.swing.JLabel();
        jButtonNuevoSocio = new javax.swing.JButton();
        jButtonBajaSocio = new javax.swing.JButton();
        jButtonActualizacionSocio = new javax.swing.JButton();
        jButtonFiltro = new javax.swing.JButton();
        jTextFieldBuscador = new javax.swing.JTextField();
        jComboBoxFiltro = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        jTableSocios.setBackground(new java.awt.Color(255, 255, 255));
        jTableSocios.setBorder(new javax.swing.border.MatteBorder(null));
        jTableSocios.setForeground(new java.awt.Color(0, 0, 0));
        jTableSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableSocios);

        jLabelGestionSocios.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabelGestionSocios.setForeground(new java.awt.Color(51, 204, 255));
        jLabelGestionSocios.setText("Gestión de Socios");

        jButtonNuevoSocio.setBackground(new java.awt.Color(102, 204, 255));
        jButtonNuevoSocio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonNuevoSocio.setForeground(new java.awt.Color(0, 0, 0));
        jButtonNuevoSocio.setText("Nuevo Socio");
        jButtonNuevoSocio.setActionCommand("NuevoSocio");
        jButtonNuevoSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoSocioActionPerformed(evt);
            }
        });

        jButtonBajaSocio.setBackground(new java.awt.Color(102, 204, 255));
        jButtonBajaSocio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBajaSocio.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBajaSocio.setText("Baja de Socio");
        jButtonBajaSocio.setActionCommand("BajaSocio");
        jButtonBajaSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaSocioActionPerformed(evt);
            }
        });

        jButtonActualizacionSocio.setBackground(new java.awt.Color(102, 204, 255));
        jButtonActualizacionSocio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonActualizacionSocio.setForeground(new java.awt.Color(0, 0, 0));
        jButtonActualizacionSocio.setText("Actualización de Socio");
        jButtonActualizacionSocio.setActionCommand("ActualizacionSocio");

        jButtonFiltro.setBackground(new java.awt.Color(204, 204, 204));
        jButtonFiltro.setForeground(new java.awt.Color(0, 0, 0));
        jButtonFiltro.setText("🔎");
        jButtonFiltro.setActionCommand("filtro");
        jButtonFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltroActionPerformed(evt);
            }
        });

        jTextFieldBuscador.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldBuscador.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jTextFieldBuscador.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldBuscador.setCaretColor(new java.awt.Color(0, 0, 0));
        jTextFieldBuscador.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscadorActionPerformed(evt);
            }
        });

        jComboBoxFiltro.setBackground(new java.awt.Color(204, 204, 204));
        jComboBoxFiltro.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin filtro", "Nombre", "DNI", "Categoría", "Teléfono" }));
        jComboBoxFiltro.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButtonNuevoSocio)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBajaSocio)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonActualizacionSocio)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelGestionSocios)
                .addContainerGap(723, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFiltro)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelGestionSocios)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonFiltro)
                            .addComponent(jComboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevoSocio)
                    .addComponent(jButtonBajaSocio)
                    .addComponent(jButtonActualizacionSocio))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBajaSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBajaSocioActionPerformed

    private void jButtonNuevoSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNuevoSocioActionPerformed

    private void jButtonFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFiltroActionPerformed

    private void jTextFieldBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonActualizacionSocio;
    public javax.swing.JButton jButtonBajaSocio;
    public javax.swing.JButton jButtonFiltro;
    public javax.swing.JButton jButtonNuevoSocio;
    public javax.swing.JComboBox<String> jComboBoxFiltro;
    public javax.swing.JLabel jLabelGestionSocios;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableSocios;
    public javax.swing.JTextField jTextFieldBuscador;
    // End of variables declaration//GEN-END:variables
}
